version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./devops/go/Dockerfile
    command: go run ./http/server.go
    ports:
      - 8080:8080
    volumes:
      - .:/go/src
    user: go
    working_dir: /go/src
